---
- name: Create virtual machine
  hosts: localhost
  connection: local

  vars:
    ssh_key: ansible-control-node
    security_group: SSH-control-node 
    security_groups: default,{{ security_group }} # don't add spaces here!

  vars_files:
    - vars

  tasks:
    - name: Create security group
      os_security_group: name={{ security_group }}

    - name: Add rule to security group to all ssh from current system
      os_security_group_rule:
        security_group: "{{ security_group }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: "{{ control_node_floating_ip }}/32"

    - name: Create a virtual machine
      register: result
      openstack.cloud.server:
        name: mlflow_env
        image: Ubuntu-20.04
        flavor: "{{ vm_flavor }}"
        key_name: "{{ ssh_key }}"
        security_groups: "{{ security_groups }}"
      until: (result.openstack is defined)
   
    - name: Store the auto-allocated floating IP address
      set_fact: floating_ip={{ result.openstack.public_v4 }}

    - name: Create inventory.txt with host information
      ansible.builtin.shell: echo "[mlflow_env]\n{{ floating_ip }} ansible_user=ubuntu" > inventory.txt

    - name: Clear ssh known_hosts
      known_hosts: name={{ floating_ip }} state=absent
      when: result is changed

    - name: Wait for instance to be ready
      wait_for: host={{ floating_ip }} port=22 search_regex=OpenSSH

- name: Create a volume for tracking server storage
  hosts: localhost
  connection: local

  vars_files:
    - vars
  
  tasks:
    - name: Create a volume
      openstack.cloud.volume:
        size: "{{ tracking_storage_size_in_gb }}"
        display_name: tracking_server_storage
        state: present

