---
# Current: creates Virtual machine and sets up security requirements
- name: Create virtual machine on cPouta
  hosts: localhost # The OpenStack modules run on your local machine.
  connection: local

  vars:
    ssh_key: ansible-control-node
    security_group: SSH-desktop
    security_groups: default,{{ security_group }} # don't add spaces here!

  tasks:
 #   - debug: var=hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]    
    - name: Create security group
      os_security_group: name={{ security_group }}

    - name: Add rule to security group to allow http from the internet
      os_security_group_rule:
        security_group: "{{ security_group }}"
        protocol: tcp
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0

    - name: Add rule to security group to all ssh from current system
      os_security_group_rule:
        security_group: "{{ security_group }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: "{{ ansible_default_ipv4.address }}/32"

    - name: Create a virtual machine
      register: result
      openstack.cloud.server:
        name: mlflow_env
        image: Ubuntu-20.04
        flavor: standard.small
        key_name: "{{ ssh_key }}"
        security_groups: "{{ security_groups }}"
      until: (result.openstack is defined)
   
    - name: Store the auto-allocated floating IP address
      set_fact: floating_ip={{ result.openstack.public_v4 }}

    - name: Add new host to inventory
      add_host: name={{ floating_ip }} groups=new

    - name: clear ssh known_hosts
      known_hosts: name={{ floating_ip }} state=absent
      when: result is changed

    - name: Wait for instance to be ready
      wait_for: host={{ floating_ip }} port=22 search_regex=OpenSSH delay=60
