---
- name: Shut down tracking
  hosts: mlflow_env
  become: yes

  tasks:
    - name: Shut down the remote tracking server
      ansible.builtin.shell: sudo kill -9 `sudo lsof -t -i:5000`
      ignore_errors: yes

    - name: Unmount volume
      ansible.builtin.shell: sudo umount /dev/vdb

- name: Detach volume, execute resize and re-attach volume
  hosts: localhost
  connection: local
  
  vars_files:
    - vars.txt

  tasks:
    - name: Detach volume
      os_server_volume:
        state: absent
        server: mlflow_env
        volume: tracking_server_storage
        device: /dev/vdb

    - name: Execute resize
      ansible.builtin.shell: openstack server resize --flavor {{ vm_flavor }} mlflow_env

    - name: Confirm resize
      ansible.builtin.shell: openstack server resize confirm mlflow_env

    - name: Re-attach volume
      os_server_volume:
        state: present
        server: mlflow_env
        volume: tracking_server_storage
        device: /dev/vdb

- name: Restart tracking
  hosts: mlflow_env
  become: yes

  tasks:
    - name: Re-mount volume
      ansible.builtin.shell: sudo mount /dev/vdb /media/volume

    - name: Re-start tracking server with 10h time limit
      ansible.builtin.shell: mlflow server --backend-store-uri sqlite:////media/volume/metrics_store/mlflow.db --default-artifact-root /media/volume/artifact_store --host 0.0.0.0 &
      async: 36000
      poll: 0
 


