---
 - name: Run mlflow project
   hosts: mlflow_env
   become: yes

    vars_files:
    - vars

   tasks:
     - name: Clone mlproject repository
       ansible.builtin.git:
         repo: "{{ github_uri }}"
         dest: '/home/ubuntu/mlflow-project'
       
     - name: Build docker image
       ansible.builtin.shell: cd /home/ubuntu/mlflow-project && docker build -t {{ image_name }} -f Dockerfile .

     - name: Run mlflow project
       ansible.builtin.shell: mlflow run mlflow-project

# later version: send results to a remote tracking server
     - name: Zip the mlruns directory
       archive:
         path: /home/ubuntu/mlruns/*
         dest: /home/ubuntu/mlruns.zip
         format: zip

     - name: Copy zip to control node
       fetch:
         src: /home/ubuntu/mlruns.zip
         dest: /home/ubuntu/
