---
 - name: Run mlflow project
   hosts: mlflow_env
   become: yes

   vars:
     github_uri: https://github.com/korolainenriikka/mlflow_test.git
     image_name: mnist-dockerized

   tasks:
     - name: Clone mlproject repository
       ansible.builtin.git:
         repo: "{{ github_uri }}"
         dest: '/home/ubuntu/mnist-project'
       
     - name: Build docker image
       ansible.builtin.shell: cd /home/ubuntu/mnist-project && docker build -t mnist-dockerized -f Dockerfile .

     - name: Run mlflow project
       ansible.builtin.shell: mlflow run mnist-project

# later version: send results to a remote tracking server
     - name: Zip the mlruns directory
       archive:
         path: /home/ubuntu/mlruns/*
         dest: /home/ubuntu/mlruns.zip
         format: zip

     - name: Copy zip to control node
       fetch:
         src: /home/ubuntu/mlruns.zip
         dest: /home/ubuntu

 - name: Unzip mlruns on control node
   hosts: localhost
   become: yes

   tasks:
     - name: Install unzip
       apt: 
         name: unzip

     - name: Create directory for saving of mlruns
       ansible.builtin.shell: mkdir /home/ubuntu/mlruns

     - name: Unzip mlruns
       unarchive:
         src: /home/ubuntu/128.214.252.158/home/ubuntu/mlruns.zip
         dest: /home/ubuntu/mlruns/


