---
 - name: Run mlflow project
   hosts: mlflow_env

   vars_files:
     - vars

   tasks:
     - name: Clone mlproject repository
       ansible.builtin.git:
         repo: "{{ github_uri }}"
         dest: '/home/ubuntu/mlflow-project'
       become: yes
       
     - name: Build docker image
       ansible.builtin.shell: cd /home/ubuntu/mlflow-project{{ entrypoint }} && docker build -t {{ image_name }} -f Dockerfile .
       become: yes

     - name: Run mlflow project
       ansible.builtin.shell: mlflow run --experiment-name {{ experiment_name }} -A net=host mlflow-project{{ entrypoint }} -P vm-size={{ vm_flavor }} github-uri={{ github_uri }} {{ hyperparameters }}
       environment:
         MLFLOW_TRACKING_URI: http://localhost:5000

