---
- name: Resize the environment
  hosts: localhost
  connection: local

  vars_files:
    - vars.txt

  tasks:
    - name: Update the virtual machine size
      ansible.builtin.shell: openstack server resize --flavor {{ vm_flavor }} mlflow_env

    - name: Sleep 30 seconds to wait for resize
      ansible.builtin.pause: minutes=1

    - name: Confirm resize
      ansible.builtin.shell: openstack server resize confirm mlflow_env

    - name: Re-launch the tracking server
      ansible.builtin.shell: mlflow server --backend-store-uri sqlite:////media/volume/metrics_store/mlflow.db --default-artifact-root /media/volume/artifact_store --host 0.0.0.0 &
      async: 36000
      poll: 0
