---
- name: Resize the environment
  hosts: localhost
  connection: local

  vars_files:
    - vars.txt

  tasks:
    - name: Update the virtual machine size
      ansible.builtin.shell: openstack server resize --flavor {{ vm_flavor }} mlflow_env

    - name: Sleep 30 seconds to wait for resize
      ansible.builtin.pause: minutes=1

    - name: Confirm resize
      ansible.builtin.shell: openstack server resize confirm mlflow_env

