---
- name: Mount and prepare tracking server on volume
  hosts: mlflow_env
  become: yes
  become_user: root
  
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server

    # this one currently does not work! if not working the mount task gives openstacksdk is required -error
    # manual ssh and sudo pip install openstacksdk works
    - name: Install pip requirements (openstacksdk, pymysql)
      pip:
        name: 
          - openstacksdk
          - pymysql 
        executable: pip3
      become_user: root
      become: yes
    
    - name: Mount volume to the machine
      openstack.cloud.server_volume:
        server: mlflow_env
        volume: tracking_server_storage

    - name: Prepare file system on the volume
      debug: msg="we preppin file system"

    - name: Edit MySQL storage pointer to save on volume
      debug: msg="changin save point"

      #mysql prep commands in shell/mysql:
      #mkdir artifacts
      #sudo mlflow server --backend-store-uri mysql+pymysql://root:@localhost:3306/tracking --default-artifact-root /home/ubuntu/artifacts --host 0.0.0.0 
   

    - name: Create a MySQL database meeting tracking server requirements
      community.mysql.mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: true
        name: tracking_db
        state: present

    - name: Change user authentication plugin in mysql
      community.mysql.mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: tracking_server_user
        plugin: mysql_native_password
        state: present 

