---
- name: Mount and prepare tracking server on volume
  hosts: mlflow_env
  become: yes
  #vars_prompt:
  # - name: OS_PASSWORD
  #  prompt: Enter your OpenStack password
  
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server

    # this one currently does not work! if not working the mount task gives openstacksdk is required -error
    # manual ssh and sudo pip install openstacksdk works
    - name: Install volume mounting requirements (openstacksdk)
      pip:
        name: virtualenv
        executable: pip3
      become_user: root
      become: yes

    - name: Copy openstackrc to mlflow env
      ansible.builtin.copy:
        src: /home/ubuntu/openrc.sh
        dest: /home/ubuntu

    - name: Prepare file system on the volume
      debug: msg="we preppin file system"

    - name: Edit MySQL storage pointer to save on volume
      debug: msg="changin save point"

      #mysql prep commands in shell/mysql:
      #in mysql: CREATE DATABASE tracking;
      #mkdir artifacts
      #sudo pip install pymysql
      #in mysql: USE mysql;
      #in mysql: UPDATE user SET plugin='mysql_native_password' WHERE User='root';
      #in mysql: FLUSH PRIVILEGES;
      #in mysql: exit;
      #sudo mlflow server --backend-store-uri mysql+pymysql://root:@localhost:3306/tracking --default-artifact-root /home/ubuntu/artifacts --host 0.0.0.0 
    - name: Create a MySQL database meeting tracking server requirements
      community.mysql.mysql_db:
        name: tracking_db
        state: present

    - name: Change root user authentication plugin in mysql
      community.mysql.mysql_user:
        name: root
        plugin: mysql_native_password
        state: present

