---
- name: Prepare volume and launch the tracking server
  hosts: mlflow_env
  become: yes
  
  tasks:
    - name: Check if metrics store      
    - name: Copy volume setup script to mlflow env
      ansible.builtin.copy:
        src: /home/ubuntu/mlflow_on_openstack_automated/volumesetup.sh
        dest: /home/ubuntu

    - name: chmod +x volumesetup
      ansible.builtin.shell: sudo chmod +x volumesetup.sh
    
    - name: Run the volume setup script
      ansible.builtin.expect:
        command: /home/ubuntu/volumesetup.sh
        responses:
          "(.*)Yes/No?(.*)": Yes
          "Proceed anyway? (y,N)": y

    - name: Install sqlite3
      apt: name=sqlite

    - name: Launch the tracking server with 10h time limit
      ansible.builtin.shell: mlflow server --backend-store-uri sqlite:////media/volume/metrics_store/mlflow.db --default-artifact-root /media/volume/artifact_store --host 0.0.0.0 &
      async: 36000
      poll: 0

